export const enum SportRank {
  CANDIDATE_FOR_MASTER_OF_SPORT = 'CANDIDATE_FOR_MASTER_OF_SPORT',
  FIRST_DEGREE = 'FIRST_DEGREE',
  SECOND_DEGREE = 'SECOND_DEGREE',
  THIRD_DEGREE = 'THIRD_DEGREE',
  FIRST_JUNIOR_DEGREE = 'FIRST_JUNIOR_DEGREE',
  SECOND_JUNIOR_DEGREE = 'SECOND_JUNIOR_DEGREE',
  THIRD_JUNIOR_DEGREE = 'THIRD_JUNIOR_DEGREE',
  CANDIDATE_FOR_MASTER_OF_SPORT_AMONG_DISABLED = 'CANDIDATE_FOR_MASTER_OF_SPORT_AMONG_DISABLED',
  FIRST_DEGREE_AMONG_DISABLED = 'FIRST_DEGREE_AMONG_DISABLED',
  SECOND_DEGREE_AMONG_DISABLED = 'SECOND_DEGREE_AMONG_DISABLED',
  THIRD_DEGREE_AMONG_DISABLED = 'THIRD_DEGREE_AMONG_DISABLED',
  FIRST_JUNIOR_DEGREE_AMONG_DISABLED = 'FIRST_JUNIOR_DEGREE_AMONG_DISABLED',
  SECOND_JUNIOR_DEGREE_AMONG_DISABLED = 'SECOND_JUNIOR_DEGREE_AMONG_DISABLED',
  THIRD_JUNIOR_DEGREE_AMONG_DISABLED = 'THIRD_JUNIOR_DEGREE_AMONG_DISABLED',
  MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_OF_INTERNATIONAL_CLASS = 'MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_OF_INTERNATIONAL_CLASS',
  MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS = 'MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS',
  MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_OF_INTERNATIONAL_CLASS_AMONG_DISABLED = 'MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_OF_INTERNATIONAL_CLASS_AMONG_DISABLED',
  MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_AMONG_DISABLED = 'MASTER_OF_SPORT_OF_REPUBLIC_OF_BELARUS_AMONG_DISABLED',
}

export interface EnumModel<T> {
  id: number;
  name: T;
  description: string;
}

export interface KnowledgeBaseResponse {
  sportRanks: EnumModel<SportRank>[];
}
